name: GitHub Actions Demo #Automate Job
run-name: ${{ github.actor }} is testing oout Github Actions
on: [push]
jobs:
  automate-jobs:
    runs-on: ubuntu-latest
    steps:
      -name: Automat Job
      run: echo "Welcomet to Automate Job"
